"""Add user_projects and project_builds tables

Revision ID: 01208acfdcbd
Revises: 3081328a7e62
Create Date: 2025-12-09 21:46:53.987225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01208acfdcbd'
down_revision: Union[str, Sequence[str], None] = '3081328a7e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('is_auto_deploy_enabled', sa.Boolean(), nullable=False),
    sa.Column('domain_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('topology_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('env_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_builds',
    sa.Column('build_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('build_version', sa.Integer(), nullable=False),
    sa.Column('build_date', sa.DateTime(), nullable=False),
    sa.Column('build_status', sa.Enum('queued', 'in_process', 'success', 'failed', name='build_statuses'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['user_projects.project_id'], ),
    sa.PrimaryKeyConstraint('build_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_builds')
    op.drop_table('user_projects')
    # ### end Alembic commands ###
