"""add column env_variables for user projects

Revision ID: 42c4fd4a6ba9
Revises: cedf10955ca6
Create Date: 2026-01-08 21:44:07.245271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42c4fd4a6ba9'
down_revision: Union[str, Sequence[str], None] = 'cedf10955ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('env_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'env_vars')
    # ### end Alembic commands ###
