"""add column env_variables for user projects

Revision ID: 53d4a5ccb3e0
Revises: 42c4fd4a6ba9
Create Date: 2026-01-08 23:17:36.061512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d4a5ccb3e0'
down_revision: Union[str, Sequence[str], None] = '42c4fd4a6ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('mirror_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'mirror_name')
    # ### end Alembic commands ###
