"""add column commit_id for project build.

Revision ID: 65e8346a7912
Revises: 53d4a5ccb3e0
Create Date: 2026-01-09 02:01:52.833451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e8346a7912'
down_revision: Union[str, Sequence[str], None] = '53d4a5ccb3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_builds', sa.Column('commit_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_builds', 'commit_id')
    # ### end Alembic commands ###
