"""add deployment_plan and plan_status to user_projects

Revision ID: b67a98f155f0
Revises: h2i3j4k5l6m7
Create Date: 2026-04-15 14:39:49.527161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b67a98f155f0'
down_revision: Union[str, Sequence[str], None] = 'h2i3j4k5l6m7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('deployment_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_projects', sa.Column('plan_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'plan_status')
    op.drop_column('user_projects', 'deployment_plan')
    # ### end Alembic commands ###
